=== Arcianne/seasonsofus/asio_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">

    <xsd:element name="portfolio">
        <xsd:complexType>
            <xsd:sequence>

                <xsd:element name="student">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="firstname" type="xsd:string"/>
                            <xsd:element name="lastname" type="xsd:string"/>
                            <xsd:element name="course" type="xsd:string"/>
                            <xsd:element name="yearlevel" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="about" type="xsd:string"/>

                <xsd:element name="skills">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="skill" type="xsd:string" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="projects">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="project" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="title" type="xsd:string"/>
                                        <xsd:element name="description" type="xsd:string"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="contact">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="email" type="xsd:string"/>
                            <xsd:element name="github" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== Arcianne/seasonsofus/asio_portfolio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="asio_transform.xsl"?>

<portfolio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="asio_schema.xsd">

    <student>
        <firstname>Shanielle Anne</firstname>
        <lastname>Asio</lastname>
        <course>BS Information Technology</course>
        <yearlevel>4th Year</yearlevel>
    </student>

    <about>
        Hi! My name is Shanielle Anne Asio. I am a 4th-year IT student passionate
        about web development and design.
    </about>

    <skills>
        <skill>HTML</skill>
        <skill>CSS</skill>
        <skill>JavaScript</skill>
        <skill>Python</skill>
    </skills>

    <projects>
        <project>
            <title>Gourmet Discoveries</title>
            <description>A web application that allows users to explore Filipino cuisines.</description>
        </project>
    </projects>

    <contact>
        <email>shanielleanne27@gmail.com</email>
        <github>https://github.com/shnll-a</github>
    </contact>

</portfolio>
